package com.example.saasutil.enums;

/**
 * 运营系统日志采集
 */
public enum OperationContentType {
  //提交订单
  ORDER_CLOSE,
  //待投保
  ORDER_WAIT,
  //待风控审核
  ORDER_RISK_CHECK,
  //风控审核失败
  ORDER_RISK_CHECK_FAIL,
  //待保险公司审核
  ORDER_INSURANCE_CHECK,
  //保险公司审核失败
  ORDER_INSURANCE_CHECK_FAIL,
  //待支付
  ORDER_PAY_WAIT,
  //已支付
  ORDER_PAY,
  //订单完成
  ORDER_FINISH,
  //比对失败
  PAYMENT_BASIC_NOT_MATCH,
  //基本户比对成功
  PAYMENT_BASIC_MATCH,
  //支付链接失效重置
  PAYMENT_INVALID,
  //获取支付链接
  PAYMENT_GET_URL,
  //获取对账文件
  PAYMENT_GET_FILE,
  //查询对账文件
  PAYMENT_SEARCH,
  //更新保单号
  PAYMENT_UPDATE_POLICY_NO,
  //退费
  PAYMENT_REFUND,
  //金额错误
  PAYMENT_AMOUNT_NOT_MATCH,
  //提交支付遇到问题
  PAYMENT_QUESTION,
  //确认为基本户
  PAYMENT_CONFIRM_BASIC,
  //确认为非基本户
  PAYMENT_CONFIRM_NOT_BASIC,
  //保单关闭
  POLICY_CLOSE,
  //保险公司已出单待通知交易中心
  POLICY_NOT_ACTIVE,
  //待批改（还原）
  POLICY_REVERT_WAIT,
  //保险公司批改失败
  POLICY_REVERT_FAIL,
  //保险公司已批改
  POLICY_ACTIVE,
  //保单已过期
  POLICY_EXPIRE,
  //待审核
  REFUND_WAIT,
  //待完善退费信息
  REFUND_FILL_ACCOUNT,
  //审核未通过
  REFUND_FAIL,
  //待退款
  REFUND_PAY_WAIT,
  //已退款
  REFUND_PAY,
  //退保完成
  REFUND_FINISH,
  //已作废
  INVOICE_CLOSE,
  //未开票
  INVOICE_NO,
  //已开票
  INVOICE_HAVE,
  //已退保
  CLAIM_CLOSE,
  //等待理赔
  CLAIM_WAIT,
  //受理失败
  CLAIM_FAIL,
  //已受理理赔
  CLAIM,
  //处理中
  CLAIM_DEALING,
  //理赔完成
  CLAIM_COMPLETED,
  PROJECT_DELAY,
  BID_NOTIFY,
  BID_NOTICE,
  //提交基本户信息
  SUBMIT_BASIC,
  PAY_PLATFORM_TRANSFER,
  //还原
  REVERT_TC_NOTICE_HANDLER,
  PAY_TC_NOTICE_HANDLER
}
