
package com.example.saasutil.service.xian;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IElecGuaranteeLetterServicePortType", targetNamespace = "http://service.deposit.gtm.glodon/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IElecGuaranteeLetterServicePortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.deposit.gtm.glodon/")
    @RequestWrapper(localName = "getEnterpriseInfo", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.GetEnterpriseInfo")
    @ResponseWrapper(localName = "getEnterpriseInfoResponse", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.GetEnterpriseInfoResponse")
    public String getEnterpriseInfo(
        @WebParam(name = "arg0", targetNamespace = "http://service.deposit.gtm.glodon/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.deposit.gtm.glodon/")
    @RequestWrapper(localName = "getProjectInfo", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.GetProjectInfo")
    @ResponseWrapper(localName = "getProjectInfoResponse", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.GetProjectInfoResponse")
    public String getProjectInfo(
        @WebParam(name = "arg0", targetNamespace = "http://service.deposit.gtm.glodon/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.deposit.gtm.glodon/")
    @RequestWrapper(localName = "submitGuaranteeInfo", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.SubmitGuaranteeInfo")
    @ResponseWrapper(localName = "submitGuaranteeInfoResponse", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.SubmitGuaranteeInfoResponse")
    public String submitGuaranteeInfo(
        @WebParam(name = "arg0", targetNamespace = "http://service.deposit.gtm.glodon/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.deposit.gtm.glodon/")
    @RequestWrapper(localName = "updateGuaranteeInfo", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.UpdateGuaranteeInfo")
    @ResponseWrapper(localName = "updateGuaranteeInfoResponse", targetNamespace = "http://service.deposit.gtm.glodon/", className = "com.cngongbao.basic.platform.util.glodon.gtm.deposit.service.UpdateGuaranteeInfoResponse")
    public String updateGuaranteeInfo(
        @WebParam(name = "arg0", targetNamespace = "http://service.deposit.gtm.glodon/")
        String arg0);

}
