
package com.example.saasutil.service.xian;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IElecGuaranteeLetterService", targetNamespace = "http://service.deposit.gtm.glodon/", wsdlLocation = "http://124.115.168.54:9883/elecGuaranteeLetterService?wsdl")
public class IElecGuaranteeLetterService
    extends Service
{

    private  static URL IELECGUARANTEELETTERSERVICE_WSDL_LOCATION;
    private  static WebServiceException IELECGUARANTEELETTERSERVICE_EXCEPTION;
    private final static QName IELECGUARANTEELETTERSERVICE_QNAME = new QName("http://service.deposit.gtm.glodon/", "IElecGuaranteeLetterService");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://124.115.168.54:9883/elecGuaranteeLetterService?wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//
//    }

    private static URL __getWsdlLocation(String webServiceUrl) {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(webServiceUrl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IELECGUARANTEELETTERSERVICE_WSDL_LOCATION = url;
        IELECGUARANTEELETTERSERVICE_EXCEPTION = e;
        return IELECGUARANTEELETTERSERVICE_WSDL_LOCATION;
    }

    public IElecGuaranteeLetterService(String webServiceUrl) {
        super(__getWsdlLocation(webServiceUrl), IELECGUARANTEELETTERSERVICE_QNAME);
    }

    public IElecGuaranteeLetterService(String webServiceUrl,WebServiceFeature... features) {
        super(__getWsdlLocation(webServiceUrl), IELECGUARANTEELETTERSERVICE_QNAME, features);
    }

    public IElecGuaranteeLetterService(URL wsdlLocation) {
        super(wsdlLocation, IELECGUARANTEELETTERSERVICE_QNAME);
    }

    public IElecGuaranteeLetterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IELECGUARANTEELETTERSERVICE_QNAME, features);
    }

    public IElecGuaranteeLetterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IElecGuaranteeLetterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IElecGuaranteeLetterServicePortType
     */
    @WebEndpoint(name = "IElecGuaranteeLetterServicePort")
    public IElecGuaranteeLetterServicePortType getIElecGuaranteeLetterServicePort() {
        return super.getPort(new QName("http://service.deposit.gtm.glodon/", "IElecGuaranteeLetterServicePort"), IElecGuaranteeLetterServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IElecGuaranteeLetterServicePortType
     */
    @WebEndpoint(name = "IElecGuaranteeLetterServicePort")
    public IElecGuaranteeLetterServicePortType getIElecGuaranteeLetterServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.deposit.gtm.glodon/", "IElecGuaranteeLetterServicePort"), IElecGuaranteeLetterServicePortType.class, features);
    }



}
