server:
  tomcat:
    uri-encoding: UTF-8
  port: 7088
spring:
  kafka:
    bootstrap-servers: 192.168.1.121:9092,192.168.1.122:9092,192.168.1.123:9092
    listener:
      missing-topics-fatal: false
      concurrency: 5
    consumer:
      max-poll-records: 50